In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [5]:
#dummies for male and female
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [6]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [7]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [8]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [9]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [10]:
inputs.Age[:30]

0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
5     29.699118
6     54.000000
7      2.000000
8     27.000000
9     14.000000
10     4.000000
11    58.000000
12    20.000000
13    39.000000
14    14.000000
15    55.000000
16     2.000000
17    29.699118
18    31.000000
19    29.699118
20    35.000000
21    34.000000
22    15.000000
23    28.000000
24     8.000000
25    38.000000
26    29.699118
27    19.000000
28    29.699118
29    29.699118
Name: Age, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)

In [12]:
len(X_train)

712

In [13]:
len(X_test)

179

In [14]:
len(inputs)

891

In [50]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [51]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8882886895212309

In [15]:
#NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [16]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
model.score(X_test,y_test)

0.7877094972067039

In [18]:
X_test[:10]

Pclass        Age      Fare  female  male
348       3   3.000000   15.9000       0     1
583       1  36.000000   40.1250       0     1
555       1  62.000000   26.5500       0     1
278       3   7.000000   29.1250       0     1
268       1  58.000000  153.4625       1     0
234       2  24.000000   10.5000       0     1
201       3  29.699118   69.5500       0     1
173       3  21.000000    7.9250       0     1
408       3  21.000000    7.7750       0     1
17        2  29.699118   13.0000       0     1

In [19]:
y_test[:10]

348    1
583    0
555    0
278    0
268    1
234    0
201    0
173    0
408    0
17     1
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [21]:
model.predict_proba(X_test[:10])

array([[9.76494197e-01, 2.35058027e-02],
       [9.03192309e-01, 9.68076908e-02],
       [8.94549882e-01, 1.05450118e-01],
       [9.78395919e-01, 2.16040806e-02],
       [6.35149456e-06, 9.99993649e-01],
       [9.74285330e-01, 2.57146695e-02],
       [9.66862471e-01, 3.31375294e-02],
       [9.87090342e-01, 1.29096576e-02],
       [9.87082545e-01, 1.29174555e-02],
       [9.76564031e-01, 2.34359692e-02]])

# SPAM MAILS

In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [24]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [25]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()
#spam = 1  ham=0

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [27]:
len(X_train)

4457

In [28]:
len(X_test)

1115

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count=v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [32]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9820627802690582

In [33]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [34]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [35]:
clf.score(X_test,y_test)

0.9820627802690582

In [36]:
clf.predict(emails)

array([0, 1], dtype=int64)

# EXERCISE

In [37]:
from sklearn import datasets
wine = datasets.load_wine()

In [38]:
dir(wine)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [39]:
wine.data[0:2]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])

In [40]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [41]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [42]:
wine.target[0:2]

array([0, 0])

In [43]:
import pandas as pd
df = pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [44]:
df['target'] = wine.target
df[50:70]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
50    13.05        1.73  2.04               12.4       92.0           2.72   
51    13.83        1.65  2.60               17.2       94.0           2.45   
52    13.82        1.75  2.42               14.0      111.0           3.88   
53    13.77        1.90  2.68               17.1      115.0           3.00   
54    13.74        1.67  2.25               16.4      118.0           2.60   
55    13.56        1.73  2.46               20.5      116.0           2.96   
56    14.22        1.70  2.30               16.3      118.0           3.20   
57    13.29        1.97  2.68               16.8      102.0           3.00   
58    13.72        1.43  2.50               16.7      108.0           3.40   
59    12.37        0.94  1.36               10.6       88.0           1.98   
60    12.33        1.10  2.28               16.0      101.0           2.05   
61    12.64        1.36  2.02               16.8      100.0           2.02   
62    13.67        1.25  1.92               18.0       94.0           2.10   
63    12.37        1.13  2.16               19.0       87.0           3.50   
64    12.17        1.45  2.53               19.0      104.0           1.89   
65    12.37        1.21  2.56               18.1       98.0           2.42   
66    13.11        1.01  1.70               15.0       78.0           2.98   
67    12.37        1.17  1.92               19.6       78.0           2.11   
68    13.34        0.94  2.36               17.0      110.0           2.53   
69    12.21        1.19  1.75               16.8      151.0           1.85   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
50        3.27                  0.17             2.91             7.20  1.12   
51        2.99                  0.22             2.29             5.60  1.24   
52        3.74                  0.32             1.87             7.05  1.01   
53        2.79                  0.39             1.68             6.30  1.13   
54        2.90                  0.21             1.62             5.85  0.92   
55        2.78                  0.20             2.45             6.25  0.98   
56        3.00                  0.26             2.03             6.38  0.94   
57        3.23                  0.31             1.66             6.00  1.07   
58        3.67                  0.19             2.04             6.80  0.89   
59        0.57                  0.28             0.42             1.95  1.05   
60        1.09                  0.63             0.41             3.27  1.25   
61        1.41                  0.53             0.62             5.75  0.98   
62        1.79                  0.32             0.73             3.80  1.23   
63        3.10                  0.19             1.87             4.45  1.22   
64        1.75                  0.45             1.03             2.95  1.45   
65        2.65                  0.37             2.08             4.60  1.19   
66        3.18                  0.26             2.28             5.30  1.12   
67        2.00                  0.27             1.04             4.68  1.12   
68        1.30                  0.55             0.42             3.17  1.02   
69        1.28                  0.14             2.50             2.85  1.28   

    od280/od315_of_diluted_wines  proline  target  
50                          2.91   1150.0       0  
51                          3.37   1265.0       0  
52                          3.26   1190.0       0  
53                          2.93   1375.0       0  
54                          3.20   1060.0       0  
55                          3.03   1120.0       0  
56                          3.31    970.0       0  
57                          2.84   1270.0       0  
58                          2.87   1285.0       0  
59                          1.82    520.0       1  
60                          1.67    680.0       1  
61                          1.59    450.0       1  
62      

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=100)

In [46]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [47]:
model.score(X_test,y_test)

1.0

In [48]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
mn.score(X_test,y_test)

0.8333333333333334